### PR TITLE
All file types

### LINKED ISSUE #7: How do I use this?
I just got this extension, and I was going to use it for **Python**, but have no idea how to use it: are the snippets supposed to be inside the string or outside?

This is my code:
```
import re
while True:
    email = input("Email Adress: ")
    m = re.match(r"([a-zA-z0-9.]+)@([a-z0-9]+\.[a-z]+)", email)
    if m is None:
        print("Invalid E-mail. Please try again.") 
    else:
        print("Username: ", m.group(1))
        print("Domain Name: ", m.group(2))
```

I want to use the `!valemail` snipped from this extension instead of `r"([a-zA-z0-9.]+)@([a-z0-9]+\.[a-z]+)"`.

### PR DESCRIPTION
**Pull request by jonathantwite**
Fixes #7 

Removed language specification, snippets now installed for all file types.

### CODE REVIEW

**Comment by monizb** [comment]
Hey @jonathantwite I am not very sure if the regex syntax for all the programming languages do remain the same, as far as I know many languages interpret many of the symbols as something else, please do let me know. Thanks!

**Comment by aasutossh** [comment]
Can't use this extension in `.vue` files.

**Comment by monizb** [comment]
> Can't use this extension in `.vue` files.

Hey @aasutossh I will soon release for Vue as well

**Comment by aasutossh** [comment]
> > Can't use this extension in `.vue` files.
> 
> Hey @aasutossh I will soon release for Vue as well

Sounds great.

**Pull request closed without merging**
